trigger:
  branches:
    include:
      - refs/tags/release_*

pool:
  vmImage: windows-latest

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'f40dfb5b-e275-4435-b647-9e634bcf8acf'
    definition: '32'
    buildVersionToDownload: 'latest'
    artifactName: 'Job'
    targetPath: '$(Pipeline.Workspace)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f40dfb5b-e275-4435-b647-9e634bcf8acf/66e29136-1631-4c2e-8c0a-0c69bc4fb6a1'